version: "3.3"

services:

  smart-home-server:
    build:
      context: .
    restart: always
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    networks:
      - homedb

networks:
  homedb:
    external: true
