# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment CI

on: [ push, pull_request ]

jobs:

  deploy_service:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" > .env
          echo "SH_KEY=${{ secrets.KEY }}" >> .env
          echo "SH_USERNAME=${{ secrets.USERNAME }}" >> .env
          echo "SH_PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "SH_AUTH2_CLIENT_ID=${{ secrets.AUTH2_CLIENT_ID }}" >> .env
          echo "SH_AUTH2_CLIENT_SECRET=${{ secrets.AUTH2_CLIENT_SECRET }}" >> .env
          echo "SH_AUTH2_REDIRECT_URI=${{ secrets.AUTH2_REDIRECT_URI }}" >> .env
          echo "SH_GOOGLE_USER_ID=${{ secrets.GOOGLE_USER_ID }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env

      - name: Copy project to the hosting
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: 20
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

      - name: Deploy project with docker in hosting
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ${{ secrets.REMOTE_TARGET }} && ./deploy.sh
          host: ${{ secrets.REMOTE_HOST }}
          port: 20
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.SERVER_SSH_KEY}}
